security:
  jwt:
    secret-key: 923f6ad7deb85d35ab7ed4a6d8691b742d284b16fbd5b69ac97638d550f532bc
    access-token-expiration-time: "#{60 * 60 * 1000}" # SpEL expression
    refresh-token-expiration-time: "#{7 * 24 * 60 * 60 * 1000}" # SpEL expression