spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/startupdb
    #    username: postgres
    #    password: 55555
    url: jdbc:postgresql://postgres1.cz62o2yusm9p.eu-north-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: davron_abdusalomov
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    locations: classpath:db/changelog/tables
logging:
  file:
    name: application.log
  level:
    org.springframework: error
security:
  jwt:
    secret-key: 923f6ad7deb85d35ab7ed4a6d8691b742d284b16fbd5b69ac97638d550f532bc
    access-token-expiration-time: 3600000  # 1 hour
    refresh-token-expiration-time: 604800000  # 7 days
