spring.datasource.url=startup24.postgres.database.azure.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=AD0077005@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.file.name=application.log
logging.level.org.springframework=error

