spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intelecta_db
    username: postgres
    password: 55555
#    url: jdbc:postgresql://postgres1.cz62o2yusm9p.eu-north-1.rds.amazonaws.com:5432/postgres
#    username: postgres
#    password: davron_abdusalomov
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/changelog/tables
logging:
  file:
    name: application.log
  level:
    org.springframework: info
    org.apache.coyote.http11: DEBUG
    org.springframework.web.multipart: DEBUG

server:
  port: 8081

security:
  jwt:
    secret-key: 2DlxFcYXg77MrywoNI/+vZ/SBf0TCZbiA45JRQOAoRt60iPH28qVEXK5CrzIwjOsYPCg6f2UDCmo6eiiPlDdUg==
    access-token-expiration-time: 3600000  # 1 hour
    refresh-token-expiration-time: 604800000  # 7 days

app:
  base-url: https://intellecta.uz
  attachments:
    path: /opt/apps/intellecta/uploads

springdoc:
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config

supabase:
  url: https://uzydopnwqfekvnspcttj.supabase.co
  service-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6eWRvcG53cWZla3Zuc3BjdHRqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDUzNTkyNSwiZXhwIjoyMDg2MTExOTI1fQ.43HhwmQdvdfEUz0T_8e64m2SL2OZK5Qf_OFmmbvDgKU

youtube:
  credentials: certificates/client_secret_web.json
  application-name: Intellecta Backend

google:
  oauth:
      client-id: ${YOUTUBE_CLIENT_ID}
      client-secret: ${YOUTUBE_CLIENT_SECRET}
      refresh-token: ${YOUTUBE_REFRESH_TOKEN}