package com.example.demo.enums;

import lombok.Getter;

@Getter
public enum PermissionEnum {
    CREATE,
    SIGN_UP,
    GET_STUDENTS_LIST,
    GET_STUDENT,
    DELETE_STUDENT,
    UPDATE_STUDENT,
    GET_TEACHERS_LIST,
    GET_TEACHER,
    DELETE_TEACHER,
    UPDATE_TEACHER,
    CREATE_GROUP,
    GET_GROUPS_LIST,
    GET_GROUP,
    DELETE_GROUP,
    UPDATE_GROUP,
    ASSIGN_STUDENT_TO_GROUP,
    DEASSIGN_STUDENT_FROM_GROUP,
    ASSIGN_TEACHER_TO_GROUP
}
